// <auto-generated />
using Datalayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Datalayer.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20211023123938_update2")]
    partial class update2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Datalayer.Entity.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Email = "Ole@eksample.dk",
                            FirstName = "Ole",
                            LastName = "Sigurd"
                        });
                });

            modelBuilder.Entity("Datalayer.Entity.CustomerLocation", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.HasKey("CustomerId", "LocationId");

                    b.HasIndex("LocationId");

                    b.ToTable("CustomerLocation");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            LocationId = 3
                        });
                });

            modelBuilder.Entity("Datalayer.Entity.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Zipcode")
                        .HasColumnType("int");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            LocationId = 1,
                            Address = "Hilmarfinsensgade 12",
                            City = "Sønderborg",
                            Country = "Denmark",
                            Zipcode = 6400
                        },
                        new
                        {
                            LocationId = 2,
                            Address = "Bredgade 33",
                            City = "Aabenraa",
                            Country = "Denmark",
                            Zipcode = 6200
                        },
                        new
                        {
                            LocationId = 3,
                            Address = "Landevejen 144",
                            City = "Aalborg",
                            Country = "Denmark",
                            Zipcode = 9029
                        });
                });

            modelBuilder.Entity("Datalayer.Entity.Manufacturer", b =>
                {
                    b.Property<int>("ManufacturerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ManufacturerId");

                    b.ToTable("Manufacturers");

                    b.HasData(
                        new
                        {
                            ManufacturerId = 1,
                            Name = "Euc syd"
                        },
                        new
                        {
                            ManufacturerId = 2,
                            Name = "Aabenraa makinfabrik"
                        });
                });

            modelBuilder.Entity("Datalayer.Entity.ManufacturerLocation", b =>
                {
                    b.Property<int>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.HasKey("ManufacturerId", "LocationId");

                    b.HasIndex("LocationId");

                    b.ToTable("ManufacturerLocation");

                    b.HasData(
                        new
                        {
                            ManufacturerId = 1,
                            LocationId = 1
                        },
                        new
                        {
                            ManufacturerId = 2,
                            LocationId = 2
                        });
                });

            modelBuilder.Entity("Datalayer.Entity.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            CustomerId = 1,
                            TotalPrice = 100.0
                        });
                });

            modelBuilder.Entity("Datalayer.Entity.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Hidden")
                        .HasColumnType("bit");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Description = "This product is an Awesome piece of craftsmanship",
                            Hidden = false,
                            ManufacturerId = 1,
                            Name = "Product2026",
                            Price = 0.96761751871910762
                        },
                        new
                        {
                            ProductId = 2,
                            Description = "This product is an Awesome piece of craftsmanship",
                            Hidden = false,
                            ManufacturerId = 1,
                            Name = "Product5064",
                            Price = 0.098140941512836588
                        },
                        new
                        {
                            ProductId = 3,
                            Description = "This product is an Awesome piece of craftsmanship",
                            Hidden = false,
                            ManufacturerId = 1,
                            Name = "Product6994",
                            Price = 0.33072846631087754
                        },
                        new
                        {
                            ProductId = 4,
                            Description = "This product is an Awesome piece of craftsmanship",
                            Hidden = false,
                            ManufacturerId = 1,
                            Name = "Product6671",
                            Price = 0.98885444225224406
                        },
                        new
                        {
                            ProductId = 5,
                            Description = "This product is an Awesome piece of craftsmanship",
                            Hidden = false,
                            ManufacturerId = 1,
                            Name = "Product6650",
                            Price = 0.21303140149127292
                        },
                        new
                        {
                            ProductId = 6,
                            Description = "This product is an Awesome piece of craftsmanship",
                            Hidden = false,
                            ManufacturerId = 1,
                            Name = "Product4344",
                            Price = 0.10333153843103514
                        },
                        new
                        {
                            ProductId = 7,
                            Description = "This product is an Awesome piece of craftsmanship",
                            Hidden = false,
                            ManufacturerId = 1,
                            Name = "Product6931",
                            Price = 0.02461951366840839
                        },
                        new
                        {
                            ProductId = 8,
                            Description = "This product is an Awesome piece of craftsmanship",
                            Hidden = false,
                            ManufacturerId = 1,
                            Name = "Product8064",
                            Price = 0.7403624703829933
                        },
                        new
                        {
                            ProductId = 9,
                            Description = "This product is an Awesome piece of craftsmanship",
                            Hidden = false,
                            ManufacturerId = 1,
                            Name = "Product9793",
                            Price = 0.35495251340556538
                        },
                        new
                        {
                            ProductId = 10,
                            Description = "This product is an Awesome piece of craftsmanship",
                            Hidden = false,
                            ManufacturerId = 1,
                            Name = "Product3178",
                            Price = 0.93979807288376527
                        },
                        new
                        {
                            ProductId = 11,
                            Description = "This product is an Awesome piece of craftsmanship",
                            Hidden = false,
                            ManufacturerId = 1,
                            Name = "Product4864",
                            Price = 0.013716898399273352
                        },
                        new
                        {
                            ProductId = 12,
                            Description = "This product is an Awesome piece of craftsmanship",
                            Hidden = false,
                            ManufacturerId = 1,
                            Name = "Product5319",
                            Price = 0.55084223325869175
                        },
                        new
                        {
                            ProductId = 13,
                            Description = "This product is an Awesome piece of craftsmanship",
                            Hidden = false,
                            ManufacturerId = 1,
                            Name = "Product4775",
                            Price = 0.8198520470503029
                        },
                        new
                        {
                            ProductId = 14,
                            Description = "This product is an Awesome piece of craftsmanship",
                            Hidden = false,
                            ManufacturerId = 1,
                            Name = "Product8128",
                            Price = 0.32081744182892957
                        },
                        new
                        {
                            ProductId = 15,
                            Description = "This product is an Awesome piece of craftsmanship",
                            Hidden = false,
                            ManufacturerId = 1,
                            Name = "Product2143",
                            Price = 0.41212658603309027
                        },
                        new
                        {
                            ProductId = 16,
                            Description = "This product is an Awesome piece of craftsmanship",
                            Hidden = false,
                            ManufacturerId = 1,
                            Name = "Product3555",
                            Price = 0.87413053627783921
                        },
                        new
                        {
                            ProductId = 17,
                            Description = "This product is an Awesome piece of craftsmanship",
                            Hidden = false,
                            ManufacturerId = 1,
                            Name = "Product2947",
                            Price = 0.65551696934528503
                        },
                        new
                        {
                            ProductId = 18,
                            Description = "This product is an Awesome piece of craftsmanship",
                            Hidden = false,
                            ManufacturerId = 1,
                            Name = "Product8715",
                            Price = 0.33351630872744897
                        },
                        new
                        {
                            ProductId = 19,
                            Description = "This product is an Awesome piece of craftsmanship",
                            Hidden = false,
                            ManufacturerId = 1,
                            Name = "Product6994",
                            Price = 0.084723982068115836
                        },
                        new
                        {
                            ProductId = 20,
                            Description = "This product is an Awesome piece of craftsmanship",
                            Hidden = false,
                            ManufacturerId = 1,
                            Name = "Product3045",
                            Price = 0.68084528515154741
                        });
                });

            modelBuilder.Entity("Datalayer.Entity.ProductImage", b =>
                {
                    b.Property<int>("ProductImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("ProductImageId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImage");
                });

            modelBuilder.Entity("Datalayer.Entity.ProductOrder", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductOrder");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            ProductId = 15,
                            Amount = 0
                        });
                });

            modelBuilder.Entity("Datalayer.Entity.CustomerLocation", b =>
                {
                    b.HasOne("Datalayer.Entity.Customer", "Customer")
                        .WithMany("Locations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Datalayer.Entity.Location", "Location")
                        .WithMany("CustomerLocations")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Datalayer.Entity.ManufacturerLocation", b =>
                {
                    b.HasOne("Datalayer.Entity.Location", "Location")
                        .WithMany("ManufacturerLocations")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Datalayer.Entity.Manufacturer", "Manufacturer")
                        .WithMany("Locations")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("Datalayer.Entity.Order", b =>
                {
                    b.HasOne("Datalayer.Entity.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Datalayer.Entity.Product", b =>
                {
                    b.HasOne("Datalayer.Entity.Manufacturer", "Manufacturer")
                        .WithMany("Products")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("Datalayer.Entity.ProductImage", b =>
                {
                    b.HasOne("Datalayer.Entity.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Datalayer.Entity.ProductOrder", b =>
                {
                    b.HasOne("Datalayer.Entity.Order", "Order")
                        .WithMany("ProductOrders")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Datalayer.Entity.Product", "Product")
                        .WithMany("ProductOrders")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Datalayer.Entity.Customer", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("Datalayer.Entity.Location", b =>
                {
                    b.Navigation("CustomerLocations");

                    b.Navigation("ManufacturerLocations");
                });

            modelBuilder.Entity("Datalayer.Entity.Manufacturer", b =>
                {
                    b.Navigation("Locations");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("Datalayer.Entity.Order", b =>
                {
                    b.Navigation("ProductOrders");
                });

            modelBuilder.Entity("Datalayer.Entity.Product", b =>
                {
                    b.Navigation("ProductImages");

                    b.Navigation("ProductOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
