// <auto-generated />
using Datalayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Datalayer.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20211026090849_imageUpdate")]
    partial class imageUpdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Datalayer.Entity.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Email = "Ole@eksample.dk",
                            FirstName = "Ole",
                            LastName = "Sigurd"
                        });
                });

            modelBuilder.Entity("Datalayer.Entity.CustomerLocation", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.HasKey("CustomerId", "LocationId");

                    b.HasIndex("LocationId");

                    b.ToTable("CustomerLocation");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            LocationId = 3
                        });
                });

            modelBuilder.Entity("Datalayer.Entity.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Zipcode")
                        .HasColumnType("int");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            LocationId = 1,
                            Address = "Hilmarfinsensgade 12",
                            City = "Sønderborg",
                            Country = "Denmark",
                            Zipcode = 6400
                        },
                        new
                        {
                            LocationId = 2,
                            Address = "Bredgade 33",
                            City = "Aabenraa",
                            Country = "Denmark",
                            Zipcode = 6200
                        },
                        new
                        {
                            LocationId = 3,
                            Address = "Landevejen 144",
                            City = "Aalborg",
                            Country = "Denmark",
                            Zipcode = 9029
                        });
                });

            modelBuilder.Entity("Datalayer.Entity.Manufacturer", b =>
                {
                    b.Property<int>("ManufacturerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ManufacturerId");

                    b.ToTable("Manufacturers");

                    b.HasData(
                        new
                        {
                            ManufacturerId = 1,
                            Name = "Euc syd"
                        },
                        new
                        {
                            ManufacturerId = 2,
                            Name = "Aabenraa makinfabrik"
                        });
                });

            modelBuilder.Entity("Datalayer.Entity.ManufacturerLocation", b =>
                {
                    b.Property<int>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.HasKey("ManufacturerId", "LocationId");

                    b.HasIndex("LocationId");

                    b.ToTable("ManufacturerLocation");

                    b.HasData(
                        new
                        {
                            ManufacturerId = 1,
                            LocationId = 1
                        },
                        new
                        {
                            ManufacturerId = 2,
                            LocationId = 2
                        });
                });

            modelBuilder.Entity("Datalayer.Entity.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            CustomerId = 1,
                            TotalPrice = 100.0
                        });
                });

            modelBuilder.Entity("Datalayer.Entity.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Hidden")
                        .HasColumnType("bit");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Description = "This product is an Awesome piece of craftsmanship",
                            Hidden = false,
                            ManufacturerId = 1,
                            Name = "Product5182",
                            Price = 0.91614782899438774
                        },
                        new
                        {
                            ProductId = 2,
                            Description = "This product is an Awesome piece of craftsmanship",
                            Hidden = false,
                            ManufacturerId = 1,
                            Name = "Product7152",
                            Price = 0.11738257488113948
                        },
                        new
                        {
                            ProductId = 3,
                            Description = "This product is an Awesome piece of craftsmanship",
                            Hidden = false,
                            ManufacturerId = 1,
                            Name = "Product5693",
                            Price = 0.92056960748535099
                        },
                        new
                        {
                            ProductId = 4,
                            Description = "This product is an Awesome piece of craftsmanship",
                            Hidden = false,
                            ManufacturerId = 1,
                            Name = "Product6001",
                            Price = 0.16037584895285584
                        },
                        new
                        {
                            ProductId = 5,
                            Description = "This product is an Awesome piece of craftsmanship",
                            Hidden = false,
                            ManufacturerId = 1,
                            Name = "Product3151",
                            Price = 0.82966394342000782
                        },
                        new
                        {
                            ProductId = 6,
                            Description = "This product is an Awesome piece of craftsmanship",
                            Hidden = false,
                            ManufacturerId = 1,
                            Name = "Product3190",
                            Price = 0.3645309570080279
                        },
                        new
                        {
                            ProductId = 7,
                            Description = "This product is an Awesome piece of craftsmanship",
                            Hidden = false,
                            ManufacturerId = 1,
                            Name = "Product8297",
                            Price = 0.64483075665534972
                        },
                        new
                        {
                            ProductId = 8,
                            Description = "This product is an Awesome piece of craftsmanship",
                            Hidden = false,
                            ManufacturerId = 1,
                            Name = "Product8913",
                            Price = 0.3670397486384212
                        },
                        new
                        {
                            ProductId = 9,
                            Description = "This product is an Awesome piece of craftsmanship",
                            Hidden = false,
                            ManufacturerId = 1,
                            Name = "Product6578",
                            Price = 0.47091319992715175
                        },
                        new
                        {
                            ProductId = 10,
                            Description = "This product is an Awesome piece of craftsmanship",
                            Hidden = false,
                            ManufacturerId = 1,
                            Name = "Product5579",
                            Price = 0.59967039460300953
                        },
                        new
                        {
                            ProductId = 11,
                            Description = "This product is an Awesome piece of craftsmanship",
                            Hidden = false,
                            ManufacturerId = 1,
                            Name = "Product8583",
                            Price = 0.44632559849243869
                        },
                        new
                        {
                            ProductId = 12,
                            Description = "This product is an Awesome piece of craftsmanship",
                            Hidden = false,
                            ManufacturerId = 1,
                            Name = "Product6467",
                            Price = 0.60020305057997025
                        },
                        new
                        {
                            ProductId = 13,
                            Description = "This product is an Awesome piece of craftsmanship",
                            Hidden = false,
                            ManufacturerId = 1,
                            Name = "Product8471",
                            Price = 0.36230171768101943
                        },
                        new
                        {
                            ProductId = 14,
                            Description = "This product is an Awesome piece of craftsmanship",
                            Hidden = false,
                            ManufacturerId = 1,
                            Name = "Product4473",
                            Price = 0.67273645553399641
                        },
                        new
                        {
                            ProductId = 15,
                            Description = "This product is an Awesome piece of craftsmanship",
                            Hidden = false,
                            ManufacturerId = 1,
                            Name = "Product3103",
                            Price = 0.27191660193350009
                        },
                        new
                        {
                            ProductId = 16,
                            Description = "This product is an Awesome piece of craftsmanship",
                            Hidden = false,
                            ManufacturerId = 1,
                            Name = "Product6495",
                            Price = 0.89286698628816152
                        },
                        new
                        {
                            ProductId = 17,
                            Description = "This product is an Awesome piece of craftsmanship",
                            Hidden = false,
                            ManufacturerId = 1,
                            Name = "Product6035",
                            Price = 0.73443883924486064
                        },
                        new
                        {
                            ProductId = 18,
                            Description = "This product is an Awesome piece of craftsmanship",
                            Hidden = false,
                            ManufacturerId = 1,
                            Name = "Product6787",
                            Price = 0.006543357393957375
                        },
                        new
                        {
                            ProductId = 19,
                            Description = "This product is an Awesome piece of craftsmanship",
                            Hidden = false,
                            ManufacturerId = 1,
                            Name = "Product2022",
                            Price = 0.58759427982736112
                        },
                        new
                        {
                            ProductId = 20,
                            Description = "This product is an Awesome piece of craftsmanship",
                            Hidden = false,
                            ManufacturerId = 1,
                            Name = "Product5941",
                            Price = 0.25120682653561555
                        });
                });

            modelBuilder.Entity("Datalayer.Entity.ProductImage", b =>
                {
                    b.Property<int>("ProductImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("ProductImageId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImage");

                    b.HasData(
                        new
                        {
                            ProductImageId = 1,
                            ImageName = "Image",
                            ImagePath = "Image.png",
                            ProductId = 1
                        },
                        new
                        {
                            ProductImageId = 2,
                            ImageName = "Image",
                            ImagePath = "Image.png",
                            ProductId = 2
                        },
                        new
                        {
                            ProductImageId = 3,
                            ImageName = "Image",
                            ImagePath = "Image.png",
                            ProductId = 3
                        },
                        new
                        {
                            ProductImageId = 4,
                            ImageName = "Image",
                            ImagePath = "Image.png",
                            ProductId = 4
                        },
                        new
                        {
                            ProductImageId = 5,
                            ImageName = "Image",
                            ImagePath = "Image.png",
                            ProductId = 5
                        },
                        new
                        {
                            ProductImageId = 6,
                            ImageName = "Image",
                            ImagePath = "Image.png",
                            ProductId = 6
                        },
                        new
                        {
                            ProductImageId = 7,
                            ImageName = "Image",
                            ImagePath = "Image.png",
                            ProductId = 7
                        },
                        new
                        {
                            ProductImageId = 8,
                            ImageName = "Image",
                            ImagePath = "Image.png",
                            ProductId = 8
                        },
                        new
                        {
                            ProductImageId = 9,
                            ImageName = "Image",
                            ImagePath = "Image.png",
                            ProductId = 9
                        },
                        new
                        {
                            ProductImageId = 10,
                            ImageName = "Image",
                            ImagePath = "Image.png",
                            ProductId = 10
                        },
                        new
                        {
                            ProductImageId = 11,
                            ImageName = "Image",
                            ImagePath = "Image.png",
                            ProductId = 11
                        },
                        new
                        {
                            ProductImageId = 12,
                            ImageName = "Image",
                            ImagePath = "Image.png",
                            ProductId = 12
                        },
                        new
                        {
                            ProductImageId = 13,
                            ImageName = "Image",
                            ImagePath = "Image.png",
                            ProductId = 13
                        },
                        new
                        {
                            ProductImageId = 14,
                            ImageName = "Image",
                            ImagePath = "Image.png",
                            ProductId = 14
                        },
                        new
                        {
                            ProductImageId = 15,
                            ImageName = "Image",
                            ImagePath = "Image.png",
                            ProductId = 15
                        },
                        new
                        {
                            ProductImageId = 16,
                            ImageName = "Image",
                            ImagePath = "Image.png",
                            ProductId = 16
                        },
                        new
                        {
                            ProductImageId = 17,
                            ImageName = "Image",
                            ImagePath = "Image.png",
                            ProductId = 17
                        },
                        new
                        {
                            ProductImageId = 18,
                            ImageName = "Image",
                            ImagePath = "Image.png",
                            ProductId = 18
                        },
                        new
                        {
                            ProductImageId = 19,
                            ImageName = "Image",
                            ImagePath = "Image.png",
                            ProductId = 19
                        },
                        new
                        {
                            ProductImageId = 20,
                            ImageName = "Image",
                            ImagePath = "Image.png",
                            ProductId = 20
                        });
                });

            modelBuilder.Entity("Datalayer.Entity.ProductOrder", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductOrder");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            ProductId = 13,
                            Amount = 0
                        });
                });

            modelBuilder.Entity("Datalayer.Entity.CustomerLocation", b =>
                {
                    b.HasOne("Datalayer.Entity.Customer", "Customer")
                        .WithMany("Locations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Datalayer.Entity.Location", "Location")
                        .WithMany("CustomerLocations")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Datalayer.Entity.ManufacturerLocation", b =>
                {
                    b.HasOne("Datalayer.Entity.Location", "Location")
                        .WithMany("ManufacturerLocations")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Datalayer.Entity.Manufacturer", "Manufacturer")
                        .WithMany("Locations")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("Datalayer.Entity.Order", b =>
                {
                    b.HasOne("Datalayer.Entity.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Datalayer.Entity.Product", b =>
                {
                    b.HasOne("Datalayer.Entity.Manufacturer", "Manufacturer")
                        .WithMany("Products")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("Datalayer.Entity.ProductImage", b =>
                {
                    b.HasOne("Datalayer.Entity.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Datalayer.Entity.ProductOrder", b =>
                {
                    b.HasOne("Datalayer.Entity.Order", "Order")
                        .WithMany("ProductOrders")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Datalayer.Entity.Product", "Product")
                        .WithMany("ProductOrders")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Datalayer.Entity.Customer", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("Datalayer.Entity.Location", b =>
                {
                    b.Navigation("CustomerLocations");

                    b.Navigation("ManufacturerLocations");
                });

            modelBuilder.Entity("Datalayer.Entity.Manufacturer", b =>
                {
                    b.Navigation("Locations");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("Datalayer.Entity.Order", b =>
                {
                    b.Navigation("ProductOrders");
                });

            modelBuilder.Entity("Datalayer.Entity.Product", b =>
                {
                    b.Navigation("ProductImages");

                    b.Navigation("ProductOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
