// <auto-generated />
using Datalayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Datalayer.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20211023102456_update")]
    partial class update
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Datalayer.Entity.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Email = "Ole@eksample.dk",
                            FirstName = "Ole",
                            LastName = "Sigurd"
                        });
                });

            modelBuilder.Entity("Datalayer.Entity.CustomerLocation", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.HasKey("CustomerId", "LocationId");

                    b.HasIndex("LocationId");

                    b.ToTable("CustomerLocation");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            LocationId = 3
                        });
                });

            modelBuilder.Entity("Datalayer.Entity.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Zipcode")
                        .HasColumnType("int");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            LocationId = 1,
                            Address = "Hilmarfinsensgade 12",
                            City = "Sønderborg",
                            Country = "Denmark",
                            Zipcode = 6400
                        },
                        new
                        {
                            LocationId = 2,
                            Address = "Bredgade 33",
                            City = "Aabenraa",
                            Country = "Denmark",
                            Zipcode = 6200
                        },
                        new
                        {
                            LocationId = 3,
                            Address = "Landevejen 144",
                            City = "Aalborg",
                            Country = "Denmark",
                            Zipcode = 9029
                        });
                });

            modelBuilder.Entity("Datalayer.Entity.Manufacturer", b =>
                {
                    b.Property<int>("ManufacturerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ManufacturerId");

                    b.ToTable("Manufacturers");

                    b.HasData(
                        new
                        {
                            ManufacturerId = 1,
                            Name = "Euc syd"
                        },
                        new
                        {
                            ManufacturerId = 2,
                            Name = "Aabenraa makinfabrik"
                        });
                });

            modelBuilder.Entity("Datalayer.Entity.ManufacturerLocation", b =>
                {
                    b.Property<int>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.HasKey("ManufacturerId", "LocationId");

                    b.HasIndex("LocationId");

                    b.ToTable("ManufacturerLocation");

                    b.HasData(
                        new
                        {
                            ManufacturerId = 1,
                            LocationId = 1
                        },
                        new
                        {
                            ManufacturerId = 2,
                            LocationId = 2
                        });
                });

            modelBuilder.Entity("Datalayer.Entity.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            CustomerId = 1,
                            TotalPrice = 100.0
                        });
                });

            modelBuilder.Entity("Datalayer.Entity.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Hidden")
                        .HasColumnType("bit");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Description = "This product is an Awesome piece of craftsmanship",
                            Hidden = false,
                            ManufacturerId = 1,
                            Name = "Product8082",
                            Price = 0.034710444060485082
                        },
                        new
                        {
                            ProductId = 2,
                            Description = "This product is an Awesome piece of craftsmanship",
                            Hidden = false,
                            ManufacturerId = 1,
                            Name = "Product4856",
                            Price = 0.82663812480244703
                        },
                        new
                        {
                            ProductId = 3,
                            Description = "This product is an Awesome piece of craftsmanship",
                            Hidden = false,
                            ManufacturerId = 1,
                            Name = "Product5682",
                            Price = 0.51493160729991816
                        },
                        new
                        {
                            ProductId = 4,
                            Description = "This product is an Awesome piece of craftsmanship",
                            Hidden = false,
                            ManufacturerId = 1,
                            Name = "Product5178",
                            Price = 0.73101369651547343
                        },
                        new
                        {
                            ProductId = 5,
                            Description = "This product is an Awesome piece of craftsmanship",
                            Hidden = false,
                            ManufacturerId = 1,
                            Name = "Product9878",
                            Price = 0.085239692165162265
                        },
                        new
                        {
                            ProductId = 6,
                            Description = "This product is an Awesome piece of craftsmanship",
                            Hidden = false,
                            ManufacturerId = 1,
                            Name = "Product8210",
                            Price = 0.30331603125823475
                        },
                        new
                        {
                            ProductId = 7,
                            Description = "This product is an Awesome piece of craftsmanship",
                            Hidden = false,
                            ManufacturerId = 1,
                            Name = "Product7107",
                            Price = 0.0031924834489787386
                        },
                        new
                        {
                            ProductId = 8,
                            Description = "This product is an Awesome piece of craftsmanship",
                            Hidden = false,
                            ManufacturerId = 1,
                            Name = "Product6297",
                            Price = 0.99779556458713281
                        },
                        new
                        {
                            ProductId = 9,
                            Description = "This product is an Awesome piece of craftsmanship",
                            Hidden = false,
                            ManufacturerId = 1,
                            Name = "Product5274",
                            Price = 0.61210196400624794
                        },
                        new
                        {
                            ProductId = 10,
                            Description = "This product is an Awesome piece of craftsmanship",
                            Hidden = false,
                            ManufacturerId = 1,
                            Name = "Product8055",
                            Price = 0.72831812907397664
                        },
                        new
                        {
                            ProductId = 11,
                            Description = "This product is an Awesome piece of craftsmanship",
                            Hidden = false,
                            ManufacturerId = 1,
                            Name = "Product9590",
                            Price = 0.84423231978166491
                        },
                        new
                        {
                            ProductId = 12,
                            Description = "This product is an Awesome piece of craftsmanship",
                            Hidden = false,
                            ManufacturerId = 1,
                            Name = "Product6207",
                            Price = 0.069197982116228893
                        },
                        new
                        {
                            ProductId = 13,
                            Description = "This product is an Awesome piece of craftsmanship",
                            Hidden = false,
                            ManufacturerId = 1,
                            Name = "Product1516",
                            Price = 0.23382461780394642
                        },
                        new
                        {
                            ProductId = 14,
                            Description = "This product is an Awesome piece of craftsmanship",
                            Hidden = false,
                            ManufacturerId = 1,
                            Name = "Product5807",
                            Price = 0.64738977777184448
                        },
                        new
                        {
                            ProductId = 15,
                            Description = "This product is an Awesome piece of craftsmanship",
                            Hidden = false,
                            ManufacturerId = 1,
                            Name = "Product1235",
                            Price = 0.69891968867691223
                        },
                        new
                        {
                            ProductId = 16,
                            Description = "This product is an Awesome piece of craftsmanship",
                            Hidden = false,
                            ManufacturerId = 1,
                            Name = "Product8877",
                            Price = 0.96120600214284191
                        },
                        new
                        {
                            ProductId = 17,
                            Description = "This product is an Awesome piece of craftsmanship",
                            Hidden = false,
                            ManufacturerId = 1,
                            Name = "Product7301",
                            Price = 0.30577615942143654
                        },
                        new
                        {
                            ProductId = 18,
                            Description = "This product is an Awesome piece of craftsmanship",
                            Hidden = false,
                            ManufacturerId = 1,
                            Name = "Product1379",
                            Price = 0.067224734494101601
                        },
                        new
                        {
                            ProductId = 19,
                            Description = "This product is an Awesome piece of craftsmanship",
                            Hidden = false,
                            ManufacturerId = 1,
                            Name = "Product5034",
                            Price = 0.84203974383046842
                        },
                        new
                        {
                            ProductId = 20,
                            Description = "This product is an Awesome piece of craftsmanship",
                            Hidden = false,
                            ManufacturerId = 1,
                            Name = "Product1332",
                            Price = 0.80672409935236167
                        });
                });

            modelBuilder.Entity("Datalayer.Entity.ProductImage", b =>
                {
                    b.Property<int>("ProductImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("ProductImageId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImage");
                });

            modelBuilder.Entity("Datalayer.Entity.ProductOrder", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductOrder");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            ProductId = 5
                        });
                });

            modelBuilder.Entity("Datalayer.Entity.CustomerLocation", b =>
                {
                    b.HasOne("Datalayer.Entity.Customer", "Customer")
                        .WithMany("Locations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Datalayer.Entity.Location", "Location")
                        .WithMany("CustomerLocations")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Datalayer.Entity.ManufacturerLocation", b =>
                {
                    b.HasOne("Datalayer.Entity.Location", "Location")
                        .WithMany("ManufacturerLocations")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Datalayer.Entity.Manufacturer", "Manufacturer")
                        .WithMany("Locations")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("Datalayer.Entity.Order", b =>
                {
                    b.HasOne("Datalayer.Entity.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Datalayer.Entity.Product", b =>
                {
                    b.HasOne("Datalayer.Entity.Manufacturer", "Manufacturer")
                        .WithMany("Products")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("Datalayer.Entity.ProductImage", b =>
                {
                    b.HasOne("Datalayer.Entity.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Datalayer.Entity.ProductOrder", b =>
                {
                    b.HasOne("Datalayer.Entity.Order", "Order")
                        .WithMany("ProductOrders")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Datalayer.Entity.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Datalayer.Entity.Customer", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("Datalayer.Entity.Location", b =>
                {
                    b.Navigation("CustomerLocations");

                    b.Navigation("ManufacturerLocations");
                });

            modelBuilder.Entity("Datalayer.Entity.Manufacturer", b =>
                {
                    b.Navigation("Locations");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("Datalayer.Entity.Order", b =>
                {
                    b.Navigation("ProductOrders");
                });

            modelBuilder.Entity("Datalayer.Entity.Product", b =>
                {
                    b.Navigation("ProductImages");
                });
#pragma warning restore 612, 618
        }
    }
}
